# Generated by Django 3.0.4 on 2020-03-20 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_away_team', to='tournament.Team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_home_team', to='tournament.Team'),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='game_players', to='tournament.Game'),
        ),
        migrations.AlterField(
            model_name='logintracker',
            name='logout_date_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='logintracker',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='team',
            name='coach_for_team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='tournament.Coach'),
        ),
    ]
